#!/usr/bin/env bash
#
# Wizard: X (Twitter) OAuth 1.0a credentials for the Odoo social_twitter /
# x_account_twitter integration on this instance.
#
# Walks you through getting the X API Key (Consumer Key) + API Secret
# (Consumer Secret) — either from your own X developer app or from AzeezTech —
# then writes them into the live Odoo DB (madarbot-postgres-1) and restarts
# Odoo so the Link Account OAuth flow can authenticate.
#
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "X (Twitter) API credentials for Odoo"

# ── Stage 1: choose the credential source ──────────────────────────────────
stage "Choose where the credentials come from"
say "The Odoo Twitter integration needs the X app's OAuth 1.0a pair:"
say "  • API Key (Consumer Key)    — short alphanumeric, ~22-25 chars"
say "  • API Secret (Consumer Secret) — longer, base64"
warn "A Bearer Token or access token will NOT work here."
note ""
note "Two ways to get them:"
step "Option A — create your own X developer app (needs an X account with"
note "   your own email/phone; you'll generate the keys in the X Developer portal)."
step "Option B — ask AzeezTech to share the API Key + API Secret of the X app"
note "   they use for this instance's OAuth integration."
if confirm "Do you already have the API Key + API Secret in hand"; then
  note "Great — skip straight to pasting them in the next stages."
else
  note "No problem. Pick the path you'll take:"
  if confirm "Create your own X developer app (Option A)"; then
    note "OK — next stage walks you through the developer portal."
  else
    warn "You'll need to ask AzeezTech for the credentials."
    note "Stage 3 will show you exactly what to request from them."
  fi
fi
pause "Press Enter to continue"

# ── Stage 2: create your own X developer app (optional path) ───────────────
stage "Create your X developer app (Option A)"
say "Only if you're creating your own app. If you have keys already, skip."
open_url "https://developer.x.com/en/portal"
step "Sign in with the X account that will own the app."
step "Go to 'Projects & Apps' → '+ New Project' (name it, e.g. 'Odoo X Integration')."
step "Inside the project, create an App."
step "Open the app → 'Keys and tokens' tab."
note "You need these two (OAuth 1.0a / Consumer):"
step "  • 'API Key' — this is the Consumer Key."
step "  • 'API Secret' — this is the Consumer Secret."
note "Regenerate them only if lost; write them down — they're shown once."
note "Access level must allow read + write (for retweets)."
warn "Do NOT use the 'Bearer Token' row — that is not the OAuth 1.0a key."
pause "Press Enter once you have the API Key + API Secret"

# ── Stage 3: request from AzeezTech (optional path) ────────────────────────
stage "Request credentials from AzeezTech (Option B)"
say "If you're not creating your own app, send AzeezTech this request:"
note ""
note "  Subject: OAuth 1.0a credentials for our Odoo X/Twitter integration"
note ""
note "  We need the X app's OAuth 1.0a (Consumer) credentials to link our"
note "  X account in Odoo (Social Marketing → Twitter/X → Link Account):"
note "    - API Key (Consumer Key)"
note "    - API Secret (Consumer Secret)"
note "  The app must have read+write access (we repost/retweet)."
note "  Do NOT send the Bearer Token — OAuth 1.0a needs the Consumer pair."
note ""
note "Share the response with the person running this wizard."
pause "Press Enter once AzeezTech has provided the pair (or you have your own)"

# ── Stage 4: capture the API Key + API Secret ──────────────────────────────
stage "Enter the X API Key + API Secret"
say "Paste the values exactly as shown in the developer portal / from AzeezTech."
note "They will be written to the live Odoo DB and kept as config parameters."
ask TWITTER_API_KEY "API Key (Consumer Key):"
ask_secret TWITTER_API_SECRET "API Secret (Consumer Secret):"
if [[ -z "$TWITTER_API_KEY" || -z "$TWITTER_API_SECRET" ]]; then
  warn "Both values are required. Re-run the wizard when you have them."
  exit 1
fi
note ""
note "Got: key=${TWITTER_API_KEY:0:6}... secret=${TWITTER_API_SECRET:0:6}..."
if ! confirm "Write these to the live Odoo DB"; then
  warn "Aborted — nothing was changed."
  exit 1
fi

# ── Stage 5: apply to live Odoo DB + restart ───────────────────────────────
stage "Apply credentials to the live Odoo DB"
say "Writing the OAuth 1.0a pair to ir_config_parameter on the live DB"
note "  (madarbot-postgres-1, db odoo_2026-08-11_22-38-33)"
note "  and forcing 'Use your own X Account' so the values are not cleared"
note "  when you switch company."
if docker compose exec -T odoo sh -c "
  PGPASSWORD=odoo psql -h madarbot-postgres-1 -U odoo -d odoo_2026-08-11_22-38-33 -v ON_ERROR_STOP=1 <<SQL
INSERT INTO ir_config_parameter (key, value, create_date, write_date, create_uid, write_uid)
VALUES
 ('social.twitter_consumer_key', '${TWITTER_API_KEY}', now(), now(), 1, 1),
 ('social.twitter_consumer_secret_key', '${TWITTER_API_SECRET}', now(), now(), 1, 1),
 ('social.twitter_use_own_account', 'True', now(), now(), 1, 1)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, write_date = now(), write_uid = 1;
COMMIT;
SQL
"; then
  say "  ✓ wrote key + secret + use_own_account=True"
else
  warn "  ✗ DB write failed — check docker compose exec odoo works."
  exit 1
fi

say "Restarting Odoo so the config cache picks up the new values…"
if docker compose restart odoo >/dev/null 2>&1; then
  say "  ✓ Odoo restarted"
else
  warn "  ✗ restart failed — run: docker compose restart odoo"
fi

say ""
say "Next: in Odoo go to Social Marketing → Twitter/X → Link Account."
say "It should now open the x.com authorize page instead of returning 400."

finish
